# Generated by Django 5.0 on 2025-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horairedisponible',
            name='capacite_max',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='horairedisponible',
            name='nombre_commandes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
