# Generated by Django 5.0 on 2025-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0002_horairedisponible_capacite_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('menu', 'Menu'), ('burger', 'Burger'), ('salade', 'Salade'), ('couscous/tajine', 'Couscous/Tajine'), ('poulet', 'Poulet'), ('pates', 'Pâtes'), ('boisson', 'Boisson'), ('dessert', 'Dessert'), ('traiteur', 'Traiteur')], max_length=100, unique=True),
        ),
    ]
