# Generated by Django 5.0 on 2025-10-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0003_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produittransforme',
            options={'ordering': ['nom']},
        ),
        migrations.AlterUniqueTogether(
            name='recetteingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recetteingredient',
            name='produit_transforme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swigo.produittransforme'),
        ),
        migrations.AlterField(
            model_name='recetteingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swigo.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='recetteingredient',
            unique_together={('recette', 'ingredient', 'produit_transforme')},
        ),
    ]
