# Generated by Django 5.0 on 2025-10-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0004_alter_produittransforme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisson',
            options={'ordering': ['plat', 'ordre_preparation'], 'verbose_name_plural': 'Cuissons'},
        ),
        migrations.AddField(
            model_name='cuisson',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions particulières pour cette cuisson'),
        ),
        migrations.AddField(
            model_name='cuisson',
            name='ordre_preparation',
            field=models.PositiveIntegerField(default=1, help_text='Ordre de préparation dans le plat'),
        ),
        migrations.AddField(
            model_name='cuisson',
            name='temperature',
            field=models.PositiveIntegerField(blank=True, help_text='Température de cuisson en °C', null=True),
        ),
        migrations.AddField(
            model_name='cuisson',
            name='temps_cuisson',
            field=models.PositiveIntegerField(blank=True, help_text='Temps de cuisson en minutes', null=True),
        ),
        migrations.AddField(
            model_name='cuisson',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('kg', 'kilogrammes'), ('l', 'litres'), ('ml', 'millilitres'), ('u', 'unités')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='plat',
            name='est_compose',
            field=models.BooleanField(default=True, help_text="Si True, le plat est composé d'ingrédients et/ou produits transformés. Si False, c'est un produit simple."),
        ),
        migrations.AddField(
            model_name='plat',
            name='produit_transforme',
            field=models.ForeignKey(blank=True, help_text='Produit transformé principal du plat (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='swigo.produittransforme'),
        ),
        migrations.AddField(
            model_name='plat',
            name='recette',
            field=models.ForeignKey(blank=True, help_text='Recette principale du plat (si le plat est un produit transformé complexe)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='swigo.recette'),
        ),
        migrations.AlterField(
            model_name='cuisson',
            name='mode_cuisson',
            field=models.CharField(choices=[('grill', 'Grill'), ('josper', 'Josper'), ('friteuse', 'Friteuse'), ('cuiseur', 'Cuiseur'), ('four', 'Four'), ('cuit_vapeur', 'Cuit vapeur'), ('sans_cuisson', 'Sans cuisson')], default='sans_cuisson', max_length=50),
        ),
        migrations.AlterField(
            model_name='cuisson',
            name='quantite',
            field=models.DecimalField(decimal_places=3, help_text='Quantité nécessaire', max_digits=10),
        ),
    ]
