# Generated by Django 5.0 on 2025-10-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0005_alter_cuisson_options_cuisson_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='produit_transforme',
            field=models.ForeignKey(blank=True, help_text='Si cet ingrédient est un produit transformé, lien vers sa recette', null=True, on_delete=django.db.models.deletion.SET_NULL, to='swigo.produittransforme'),
        ),
        migrations.AlterField(
            model_name='produittransforme',
            name='categorie',
            field=models.CharField(choices=[('boulangerie', 'Boulangerie'), ('sauces', 'Sauces & Condiments'), ('viandes', 'Viandes Poulets & Oeufs'), ('legumes', 'Légumes Préparés'), ('fromage', 'Produits Fromager'), ('desserts', 'Desserts Préparés'), ('feculents', 'Féculents')], default='boulangerie', max_length=50),
        ),
    ]
