# Generated by Django 5.0 on 2025-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0006_ingredient_produit_transforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(choices=[('menu', 'Menu'), ('burger', 'Burger'), ('salade', 'Salade'), ('crousty', 'Crousty'), ('couscous/tajine', 'Couscous/Tajine'), ('poulet', 'Poulet'), ('sides', 'Sides'), ('boisson', 'Boisson'), ('dessert', 'Dessert'), ('traiteur', 'Traiteur')], max_length=100, unique=True),
        ),
    ]
