# Generated by Django 5.0 on 2025-10-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0009_alter_categorie_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['categorie', 'ordre', 'nom_option']},
        ),
        migrations.AddField(
            model_name='option',
            name='categorie',
            field=models.CharField(choices=[('supp_viande', 'Supp viande'), ('supp_fromage', 'Supp fromage'), ('supp_croustillant', 'Supp Croustillant'), ('supp_sauce', 'Supp Sauce'), ('autre', 'Autre')], default='autre', help_text="Catégorie de l'option pour l'affichage groupé", max_length=20),
        ),
        migrations.AddField(
            model_name='option',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans la catégorie"),
        ),
    ]
