# Generated by Django 5.0 on 2025-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0010_alter_option_options_option_categorie_option_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='type_burger',
            field=models.CharField(choices=[('classique', 'Classique - Potato Buns'), ('gourmet', 'Gourmet - Buns Boulanger'), ('non_burger', 'Non applicable')], default='non_burger', help_text='Type de burger (uniquement pour les burgers)', max_length=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='categorie',
            field=models.CharField(choices=[('supp_viande', 'Extra viande'), ('supp_fromage', 'Extra fromage'), ('supp_croustillant', 'Extra Croustillant'), ('supp_sauce', 'Extra Sauce'), ('autre', 'Autre')], default='autre', help_text="Catégorie de l'option pour l'affichage groupé", max_length=20),
        ),
    ]
