# Generated by Django 5.0 on 2025-10-27 09:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0011_plat_type_burger_alter_option_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='type_plat',
            field=models.CharField(choices=[('burger', 'Burger'), ('couscous', 'Couscous'), ('crousty', 'Crousty'), ('autre', 'Autre')], default='autre', help_text='Type de plat pour gérer les options spécifiques', max_length=20),
        ),
        migrations.AlterField(
            model_name='plat',
            name='taux_tva',
            field=models.DecimalField(choices=[(Decimal('5.5'), '5.5%'), (Decimal('10.0'), '10.0%'), (Decimal('20.0'), '20.0%')], decimal_places=1, default=Decimal('10.0'), help_text='TVA en pourcentage', max_digits=4),
        ),
    ]
