# Generated by Django 5.0 on 2025-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0012_plat_type_plat_alter_plat_taux_tva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroustyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('fromage', 'Fromage au choix'), ('sauce_rouge', 'Sauce Rouge Signature'), ('sauce_erc', 'Sauce ERC au choix'), ('supplement', 'Supplément'), ('prot_veggie', 'Protéine Végétarienne')], max_length=20)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Option Crousty',
                'verbose_name_plural': 'Options Crousty',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
    ]
