# Generated by Django 5.0 on 2025-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0013_croustyoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='options_crousty',
            field=models.ManyToManyField(blank=True, to='swigo.croustyoption', verbose_name='Options Crousty'),
        ),
    ]
