# Generated by Django 5.0 on 2025-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0014_articlepanier_options_crousty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PouletOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('type_poulet', 'Type de Poulet'), ('assaisonnement', 'Assaisonnement'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce'), ('supplement', 'Supplément')], max_length=20)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Option Poulet',
                'verbose_name_plural': 'Options Poulet',
                'ordering': ['categorie', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='options_poulet',
            field=models.ManyToManyField(blank=True, to='swigo.pouletoption', verbose_name='Options Poulet'),
        ),
    ]
