# Generated by Django 5.0 on 2025-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0015_pouletoption_articlepanier_options_poulet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouletoption',
            name='categorie',
            field=models.CharField(choices=[('sauce', 'Sauce au choix'), ('supplement', 'Supplément'), ('accompagnement', 'Accompagnement')], max_length=20),
        ),
    ]
