# Generated by Django 5.0 on 2025-10-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0016_alter_pouletoption_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompagnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_supplement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accompagnement',
                'verbose_name_plural': 'Accompagnements',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='accompagnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swigo.accompagnement', verbose_name='Accompagnement'),
        ),
    ]
