# Generated by Django 5.0 on 2025-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0017_accompagnement_articlepanier_accompagnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouletoption',
            name='categorie',
            field=models.CharField(choices=[('assaisonnement', 'Assaisonnement'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce au choix'), ('supplement', 'Supplément')], max_length=20),
        ),
    ]
