# Generated by Django 5.0 on 2025-10-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0018_alter_pouletoption_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteOptionsPoulet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('assaisonnement', 'Assaisonnement'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce au choix'), ('supplement', 'Supplément')], max_length=20)),
                ('limite_selection', models.PositiveIntegerField(default=1)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_poulet', to='swigo.plat')),
            ],
            options={
                'verbose_name': "Limite d'options Poulet",
                'verbose_name_plural': "Limites d'options Poulet",
                'unique_together': {('plat', 'categorie')},
            },
        ),
    ]
