# Generated by Django 5.0 on 2025-10-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0019_limiteoptionspoulet'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiteoptionspoulet',
            name='est_obligatoire',
            field=models.BooleanField(default=True, help_text="L'utilisateur doit-il sélectionner au moins une option?"),
        ),
        migrations.AlterField(
            model_name='limiteoptionspoulet',
            name='categorie',
            field=models.CharField(choices=[('assaisonnement', 'Assaisonnement'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce'), ('supplement', 'Supplément')], max_length=20),
        ),
    ]
