# Generated by Django 5.0 on 2025-10-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0020_limiteoptionspoulet_est_obligatoire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_lie', to='swigo.commande'),
        ),
    ]
