# Generated by Django 5.0 on 2025-10-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0021_alter_panier_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='panier',
        ),
    ]
