# Generated by Django 5.0 on 2025-10-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0022_remove_commande_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_associee', to='swigo.panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_associe', to='swigo.commande'),
        ),
    ]
