# Generated by Django 5.0 on 2025-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0023_commande_panier_alter_panier_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viandecouscous',
            name='supplement_extra',
        ),
    ]
