# Generated by Django 5.0 on 2025-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0024_remove_viandecouscous_supplement_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepanier',
            name='options_poulet_quantites',
            field=models.JSONField(blank=True, default=dict, verbose_name='Quantités options poulet'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='type_plat',
            field=models.CharField(choices=[('burger', 'Burger'), ('couscous', 'Couscous'), ('crousty', 'Crousty'), ('autre', 'Autre'), ('poulet', 'Poulet')], default='autre', help_text='Type de plat pour gérer les options spécifiques', max_length=20),
        ),
    ]
