# Generated by Django 5.2.7 on 2025-11-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0024_remove_viandecouscous_supplement_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='type_plat',
            field=models.CharField(choices=[('burger', 'Burger'), ('couscous', 'Couscous'), ('crousty', 'Crousty'), ('autre', 'Autre'), ('poulet', 'Poulet')], default='autre', help_text='Type de plat pour gérer les options spécifiques', max_length=20),
        ),
    ]
