# Generated by Django 5.0 on 2025-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0025_articlepanier_options_poulet_quantites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepanier',
            name='options_poulet_quantites',
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='options_poulet_avec_quantites',
            field=models.JSONField(blank=True, default=list, verbose_name='Options Poulet avec quantités'),
        ),
    ]
