# Generated by Django 5.0 on 2025-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0025_alter_plat_type_plat'),
        ('swigo', '0026_remove_articlepanier_options_poulet_quantites_and_more'),
    ]

    operations = [
    ]
