# Generated by Django 5.0 on 2025-11-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0027_alter_choixmenu_role_alter_choixmenuarticle_role_and_more'),
        ('swigo', '0028_alter_choixmenu_role_alter_choixmenuarticle_role_and_more'),
    ]

    operations = [
    ]
