# Generated by Django 5.0 on 2025-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0029_merge_20251115_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixmenu',
            name='role',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('salade', 'Salade personnalisée'), ('couscous', 'Couscous personnalisé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='choixmenuarticle',
            name='role',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('salade', 'Salade personnalisée'), ('couscous', 'Couscous personnalisé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='composantmenufixe',
            name='role',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('salade', 'Salade personnalisée'), ('couscous', 'Couscous personnalisé')], max_length=20),
        ),
    ]
