# Generated by Django 5.0 on 2025-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0030_alter_choixmenu_role_alter_choixmenuarticle_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepanier',
            options={'ordering': ['-id'], 'verbose_name': 'Article Panier', 'verbose_name_plural': 'Articles Panier'},
        ),
        migrations.AddField(
            model_name='articlepanier',
            name='supplements_menu',
            field=models.JSONField(blank=True, default=dict, verbose_name='Suppléments menu'),
        ),
    ]
