# Generated by Django 5.0 on 2025-11-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0031_alter_articlepanier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepanier',
            options={},
        ),
    ]
