# Generated by Django 5.0 on 2025-12-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0032_alter_articlepanier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='couverts_bois',
            field=models.BooleanField(default=False, verbose_name='Couverts en bois'),
        ),
    ]
