# Generated by Django 5.0 on 2026-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0033_commande_couverts_bois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionxl',
            name='supplement',
            field=models.DecimalField(decimal_places=2, default=2.9, max_digits=5),
        ),
    ]
