# Generated by Django 5.0 on 2026-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0034_alter_optionxl_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionxl',
            name='supplement',
            field=models.DecimalField(decimal_places=2, default=3.9, max_digits=5),
        ),
    ]
