# Generated by Django 5.0 on 2026-05-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0035_alter_optionxl_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=4.9, max_digits=5),
        ),
    ]
