# Generated by Django 5.0 on 2026-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swigo', '0036_alter_panier_frais_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=3.9, max_digits=5),
        ),
    ]
