# Generated by Django 5.0 on 2026-06-25 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveSmallIntegerField(default=0)),
                ('is_sent_to_kitchen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Numéro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('grid_x', models.PositiveSmallIntegerField(default=1, verbose_name='Colonne')),
                ('grid_y', models.PositiveSmallIntegerField(default=1, verbose_name='Rangée')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('room__order', 'grid_y', 'grid_x'),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ('order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('category__order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_number', models.PositiveIntegerField()),
                ('kitchen_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='riad.diningorder')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='riad.menu')),
            ],
            options={
                'ordering': ['guest_number'],
                'unique_together': {('order', 'guest_number')},
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='riad.menu')),
            ],
            options={
                'verbose_name': 'Section de menu',
                'verbose_name_plural': 'Sections de menu',
                'ordering': ('menu__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='MenuSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='riad.menusection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='riad.product')),
            ],
            options={
                'verbose_name': 'Produit de section',
                'verbose_name_plural': 'Produits de section',
                'ordering': ('section__order', 'order'),
            },
        ),
        migrations.CreateModel(
            name='GuestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='riad.guestorder')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_choices', to='riad.menusection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_choices', to='riad.product')),
            ],
            options={
                'ordering': ('section__order',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='riad.productcategory'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('personnes', models.PositiveIntegerField(default=2)),
                ('date_heure', models.DateTimeField()),
                ('status', models.CharField(choices=[('reserved', 'Réservée'), ('installed', 'Clients installés'), ('cancelled', 'Annulée'), ('finished', 'Terminée')], default='reserved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='riad.diningtable')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date_heure'],
            },
        ),
        migrations.AddField(
            model_name='diningtable',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='riad.room', verbose_name='Salle'),
        ),
        migrations.CreateModel(
            name='TableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free', 'Libre'), ('reserved', 'Réservée'), ('installed', 'Clients installés'), ('ordering', 'Prise de commande en cours'), ('ordered', 'Commande prise'), ('drinks_served', 'Boissons servies'), ('starters_served', 'Entrées servies'), ('starters_cleared', 'Entrées débarrassées'), ('mains_served', 'Plats servis'), ('mains_cleared', 'Plats débarrassés'), ('desserts_served', 'Desserts servis'), ('desserts_cleared', 'Desserts débarrassés'), ('coffee_served', 'Thé/Café servis'), ('coffee_cleared', 'Thé/Café débarrassés'), ('bill_requested', 'Addition demandée'), ('paid', 'Addition réglée')], default='free', max_length=30)),
                ('status_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('has_drinks', models.BooleanField(default=False)),
                ('has_starters', models.BooleanField(default=False)),
                ('has_desserts', models.BooleanField(default=False)),
                ('has_coffee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='riad.reservation')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_service', to='riad.diningtable')),
            ],
            options={
                'verbose_name': 'Service de table',
                'verbose_name_plural': 'Services de table',
                'ordering': ['table__numero'],
            },
        ),
        migrations.AddField(
            model_name='diningorder',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='riad.tableservice'),
        ),
        migrations.AddConstraint(
            model_name='diningtable',
            constraint=models.UniqueConstraint(fields=('room', 'grid_x', 'grid_y'), name='unique_table_position'),
        ),
    ]
