# Generated by Django 5.0 on 2026-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ('menu__order', 'order')},
        ),
        migrations.AddField(
            model_name='menusection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menusection',
            name='max_choices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menusection',
            name='min_choices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
