# Generated by Django 5.0 on 2026-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riad', '0002_alter_menusection_options_menusection_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menusection',
            options={'ordering': ('menu__order', 'order'), 'verbose_name': 'Section de menu', 'verbose_name_plural': 'Sections de menu'},
        ),
        migrations.AddField(
            model_name='menusection',
            name='choice_type',
            field=models.CharField(choices=[('single', 'Un seul choix'), ('multiple', 'Choix multiples'), ('boolean', 'Oui / Non')], default='single', max_length=20),
        ),
    ]
