# Generated by Django 5.0 on 2026-06-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riad', '0004_kitchenticket_kitchenticketitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchenticket',
            options={'ordering': ('-sent_at',)},
        ),
        migrations.AlterModelOptions(
            name='kitchenticketitem',
            options={'ordering': ('section__order', 'product__name')},
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='course',
            field=models.CharField(choices=[('starter', 'Entrées'), ('main', 'Plats'), ('dessert', 'Desserts'), ('drinks', 'Boissons'), ('coffee', 'Thé / Café'), ('full', 'Commande complète')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='riad.tableservice'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('preparing', 'En préparation'), ('ready', 'Prêt'), ('served', 'Servi')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='riad.diningtable'),
        ),
        migrations.AddField(
            model_name='kitchenticketitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
