# Generated by Django 5.0 on 2026-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riad', '0005_alter_kitchenticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestchoice',
            name='source',
            field=models.CharField(choices=[('menu', 'Menu'), ('extra', 'Supplément'), ('offered', 'Offert')], default='menu', max_length=20),
        ),
    ]
