# Generated by Django 5.0 on 2026-06-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riad', '0006_guestchoice_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestchoice',
            options={'ordering': ('section__order', 'product__name')},
        ),
        migrations.AlterModelOptions(
            name='kitchenticket',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Bon de préparation', 'verbose_name_plural': 'Bons de préparation'},
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='station',
            field=models.CharField(choices=[('kitchen', 'Cuisine'), ('bar', 'Bar / Office')], default='kitchen', max_length=20),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='ticket_type',
            field=models.CharField(choices=[('order', 'Commande'), ('extra', 'Supplément')], default='order', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestchoice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_choices', to='riad.menusection'),
        ),
    ]
